# Generated by Django 5.1.7 on 2025-03-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ship_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="船舶编号"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="船舶名称")),
                (
                    "ship_type",
                    models.CharField(
                        choices=[
                            ("cargo", "货船"),
                            ("passenger", "客船"),
                            ("tanker", "油轮"),
                            ("fishing", "渔船"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="船舶类型",
                    ),
                ),
                ("production_year", models.IntegerField(verbose_name="生产年份")),
                ("length", models.FloatField(verbose_name="船长(米)")),
                ("tonnage", models.FloatField(verbose_name="吨位(吨)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sailing", "航行中"),
                            ("docked", "停泊中"),
                            ("maintenance", "维修中"),
                        ],
                        default="docked",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ships/",
                        verbose_name="船舶图片",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "船舶",
                "verbose_name_plural": "船舶",
                "ordering": ["-created_at"],
            },
        ),
    ]
